/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.endPanel.EASY;
import static GUI.endPanel.HARD;
import static GUI.endPanel.MEDIUM;
import Main.MainFrame;
import staticClasses.InfoTableModel;

/**
 *
 * @author zepingluo
 */
public class reviewPanel extends javax.swing.JPanel {

    MainFrame frame;
    /**
     * Creates new form reviewPanel
     */
    public reviewPanel(MainFrame frame) {
        initComponents();
        this.frame=frame;
        drawReviewTable();
    }
    public void drawReviewTable()
    {
        String[] rosterHeader = {
            "Question#", "Your Answer"
        };
        
        // Get data for table
        String[][] tableData = new String[frame.questionList.size()][rosterHeader.length];
        // Populate table with data
        for (int x = 0; x < tableData.length; x++) {
            // Athlete Info
            tableData[x][0] = ""+(x+1);
            tableData[x][1] = frame.questionList.get(x).getCorrectAnswer();
           
                   
            
        }

        // Create JTable with all our data
        reviewTable.setModel(new InfoTableModel(tableData, rosterHeader));

        reviewTable.getColumnModel().getColumn(0).setMinWidth(100);
        reviewTable.getColumnModel().getColumn(1).setMinWidth(25);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reviewTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        reviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reviewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reviewTable);

        jButton1.setText("finish your test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reviewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewTableMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() > 1) {
            int questionIndex = reviewTable.getSelectedRow();
            frame.numQuestion=questionIndex;
            frame.loadQuestion();
        }
    }//GEN-LAST:event_reviewTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame.setQuestionPanel(new endPanel(frame));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reviewTable;
    // End of variables declaration//GEN-END:variables
}
