/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Main.MainFrame;
import Main.Stopwatch;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author zepingluo
 */
public class startPanel extends javax.swing.JPanel {

    /**
     * Creates new form startPanel
     */
    MainFrame main;
    public startPanel(MainFrame main) {
        initComponents();
        this.main=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        loadTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout loadingPanelLayout = new javax.swing.GroupLayout(loadingPanel);
        loadingPanel.setLayout(loadingPanelLayout);
        loadingPanelLayout.setHorizontalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        loadingPanelLayout.setVerticalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadTest.setText("loadTest");
        loadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTestActionPerformed(evt);
            }
        });
        add(loadTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 255, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/zepingluo/Downloads/IMG_0397.JPG")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void loadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTestActionPerformed
        // TODO add your handling code here:
        //for testing only
        JDialog dialog = new JDialog(main, true);
        dialog.add(new openPanel(main));
        dialog.pack();
        dialog.setVisible(true);
        //main.filePath = "Files/Questions/data.txt";
        main.loadTest();
        int n = JOptionPane.showConfirmDialog(main,
                    "Wuold you like to sort the questions from easy to difficult", "sort",
                    JOptionPane.YES_NO_OPTION);
            switch (n) {
                case 0:
                    main.sortQuestions();
                case 1:
                   
            }
        main.loadQuestion();
        System.out.print("startPanel load Question...");
        Stopwatch stopwatch = new Stopwatch(main.timeInSeconds, main);
        main.stopwatch=stopwatch;
        main.setDisplayPanel(stopwatch);
    }//GEN-LAST:event_loadTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton loadTest;
    private javax.swing.JPanel loadingPanel;
    // End of variables declaration//GEN-END:variables
}
