/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import GUI.endPanel;

/**
 *
 * @author zepingluo
 */
public class Stopwatch extends javax.swing.JPanel {

    /**
     * Creates new form Stopwatch
     */
    MainFrame frame;
    public Stopwatch(int interval,MainFrame frame) {
        initComponents();
        go();
        this.interval=interval;
        this.frame=frame;
        
    }
    static int interval;
static Timer timer;

public void go() {
    
    int secs=100;
    int delay = 1000;
    int period = 1000;
    timer = new Timer();
    String stop;
    
    timer.scheduleAtFixedRate(new TimerTask() {

        @Override
        public void run() {
            //display.setText(""+setInterval());
            
            
            if(frame.finishBeforeTime)
            {
                display.setText("");
            }
            else   
            {
                String x = getElapsedTimeHoursMinutesFromMilliseconds(setInterval()*1000);
                
            display.setText(x);
            if(interval<10)
            {
                Font font = new Font("Rockwell Condensed", Font.PLAIN, 25);
                display.setFont(font);
                display.setBackground(Color.BLUE);
                
            }
            if(interval==0)
            {
                frame.setQuestionPanel(new endPanel(frame));
            }
            }
            
            

        }

    }, delay, period);}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();

        display.setText("START");
        display.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                displayPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void displayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_displayPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_displayPropertyChange
private static int setInterval() {
    if (interval == 1)
        timer.cancel();
    return --interval;
}

public static String getElapsedTimeHoursMinutesFromMilliseconds(long milliseconds) {
        String format = String.format("%%0%dd", 2);
        long elapsedTime = milliseconds / 1000;
        String seconds = String.format(format, elapsedTime % 60);
        String minutes = String.format(format, (elapsedTime % 3600) / 60);
        String hours = String.format(format, elapsedTime / 3600);
        String time =  hours + ":" + minutes + ":" + seconds;
        return time;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    // End of variables declaration//GEN-END:variables
}
